import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import NextTopLoader from "nextjs-toploader";
import Providers from "@/lib/Providers/Providers";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "POS Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#0D0E12]`}
      >
        <NextTopLoader
          showSpinner={false}
          //   color="#2299DD"
          //   initialPosition={0.08}
          //   crawlSpeed={200}
          //   height={3}
          //   crawl={true}
          //   easing="ease"
          //   speed={200}
          //   shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          //   template='<div className="bar" role="bar"><div className="peg"></div></div>
          // <div className="spinner" role="spinner"><div className="spinner-icon"></div></div>'
          //   zIndex={1600}
          //   showAtBottom={false}
        />
        <Providers>
          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
